version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=ipsas_accounting
      - DB_USER=postgres
      - DB_PASSWORD=
      - JWT_SECRET=
    depends_on:
      - postgres
      - redis
    volumes:
      - ./logs:/app/logs
    networks:
      - ipsas-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=ipsas_accounting
      - POSTGRES_USER=ipsas_user
      - POSTGRES_PASSWORD=ipsas_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - ipsas-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ipsas-network

volumes:
  postgres_data:
  redis_data:

networks:
  ipsas-network:
    driver: bridge
