export const IPSAS_STANDARDS = {
  IPSAS_1: "Presentation of Financial Statements",
  IPSAS_2: "Cash Flow Statements",
  IPSAS_9: "Revenue from Exchange Transactions",
  IPSAS_17: "Property, Plant and Equipment",
  IPSAS_24: "Presentation of Budget Information in Financial Statements",
} as const

export const FISCAL_PERIODS = {
  MONTHLY: "MONTHLY",
  QUARTERLY: "QUARTERLY",
  ANNUALLY: "ANNUALLY",
} as const

export const STANDARD_ACCOUNT_CODES = {
  // Assets
  CASH: "1000",
  ACCOUNTS_RECEIVABLE: "1100",
  INVENTORY: "1200",
  FIXED_ASSETS: "1500",

  // Liabilities
  ACCOUNTS_PAYABLE: "2000",
  ACCRUED_LIABILITIES: "2100",
  LONG_TERM_DEBT: "2500",

  // Net Position
  NET_INVESTMENT_CAPITAL: "3000",
  RESTRICTED_NET_POSITION: "3100",
  UNRESTRICTED_NET_POSITION: "3200",

  // Revenue
  TAX_REVENUE: "4000",
  NON_TAX_REVENUE: "4100",
  INTERGOVERNMENTAL: "4200",

  // Expenses
  PERSONNEL_SERVICES: "6000",
  OPERATING_EXPENSES: "6100",
  CAPITAL_OUTLAY: "6200",
} as const

export const PERMISSIONS = {
  // Chart of Accounts
  CREATE_ACCOUNT: "CREATE_ACCOUNT",
  UPDATE_ACCOUNT: "UPDATE_ACCOUNT",
  DELETE_ACCOUNT: "DELETE_ACCOUNT",
  VIEW_ACCOUNTS: "VIEW_ACCOUNTS",

  // General Ledger
  CREATE_JOURNAL_ENTRY: "CREATE_JOURNAL_ENTRY",
  APPROVE_TRANSACTION: "APPROVE_TRANSACTION",
  POST_TRANSACTION: "POST_TRANSACTION",
  REVERSE_TRANSACTION: "REVERSE_TRANSACTION",
  VIEW_TRANSACTIONS: "VIEW_TRANSACTIONS",

  // Reports
  VIEW_TRIAL_BALANCE: "VIEW_TRIAL_BALANCE",
  VIEW_FINANCIAL_STATEMENTS: "VIEW_FINANCIAL_STATEMENTS",
  EXPORT_REPORTS: "EXPORT_REPORTS",

  // Administration
  MANAGE_USERS: "MANAGE_USERS",
  MANAGE_ENTITIES: "MANAGE_ENTITIES",
  MANAGE_FUNDS: "MANAGE_FUNDS",
  VIEW_AUDIT_TRAIL: "VIEW_AUDIT_TRAIL",
} as const
